#!/usr/bin/env ruby

# encoding: UTF-8
$KCODE = 'UTF8' unless RUBY_VERSION >= '1.9'
require 'lib/klastfm'

if __FILE__ == $0
  t = Time.now

  klastfm = Klastfm.new
  klastfm.get_all_tracks
  klastfm.save_statistic!

  puts "Runtime: #{((Time.now-t)/60).to_i} minutes"
else
  puts "please read the README.rdoc"
end
